#!/bin/bash

source ./scripts/utils

pacman -Sy --noconfirm --quiet figlet

headline "Settig up $(hostname)"

./scripts/install-packages
./scripts/bluetooth
./scripts/setup-git "Matyas Vezer" "vezer.m@gmail.com"
./scripts/setup-snapper

